### ISSUE TITLE
Pagination for multistat-panel

### ISSUE THREAD

**Issue by mannysangra** [michaeldmoore/michaeldmoore-multistat-panel#13]
I know, that my use-case is not very typical, because we are watching lot of data. 
 Is it possible to add pagination in multistat-panel as in table panel ?
thanks

**Comment by michaeldmoore** [comment]
Sorry for the delay - I thought I responded to this some weeks ago.

I designed Multistat for monitoring applications, where it is vital to show ALL the items, ALL the time.  Pagination is really counter this objective so I don't see an easy or useful approach to adding such a feature. - Feel free to fork the source code and try to add it yourself though if you think it worth while.

Regards,
M
