### ISSUE TITLE
Stacktable bar (two fields or more) and multiples limits (low and high)

### ISSUE THREAD

**Issue by ironslow** [michaeldmoore/michaeldmoore-multistat-panel#14]
Stacktable bar (two fields or more) and multiples limits (low and high)

Thanks Michael for this great panel.

Here are two new features that I would find very useful.

1) Stacktable bar
	It would be great to be able to stack two or more numeric values on each row. 
	Ex: One label, two numeric values.
	
	Before
	![image](https://user-images.githubusercontent.com/26254774/53903818-aac2e880-4012-11e9-960a-c594629d48dc.png)

	After
	![image](https://user-images.githubusercontent.com/26254774/53903830-b1516000-4012-11e9-8db8-57fba3f0373b.png)

	
2) Multiples limits (low and high)
	Right now, those configurations are global for the entire panel. A useful feature would be to have the ability to add multiples limits (low and high) and filter them with a regex on the label.
	
	Before
	![image](https://user-images.githubusercontent.com/26254774/53903866-c4fcc680-4012-11e9-9477-10ee3f4de4cb.png)

	After
	![image](https://user-images.githubusercontent.com/26254774/53903930-e6f64900-4012-11e9-915e-e249357af470.png)

**Comment by michaeldmoore** [comment]
Wow - a suggestion complete with layout suggestions.  I love it!

It might take a while to get to this, and I'm slightly mind blown with the
idea of per-label limits - but I like the idea.

Adding the two ideas together brings a number of things to think about.
Limits might be on one or other stacked value, or maybe to the sum.  Hmm.
Maybe even the difference between two values - or the ratio.  Hmm...  Lots
to think about.

Right now, I'm buried in paid work.  But when I get some time, I will get
back to you for feedback
Cheers
M

**Comment by carloshs1993** [comment]
Hi, 

I was searching for this feature: It would be great adding the feature of stackable bars.

**Comment by michaeldmoore** [comment]
Sorry for leaving this un-answered for so very long.

Stacking bars, and/or making the thresholds bar-specific would just require too much for this already overly-complicated panel.

I might have a go at creating a stackable-bar panel in the future though, if there is enough demand (I need to check and see if there isn't anything like this already in the repository)

Cheers,
Michael Moore
