### ISSUE TITLE
Auto color each bar

### ISSUE THREAD

**Issue by marksie1988** [michaeldmoore/michaeldmoore-multistat-panel#22]
It would be great if you could have an "auto" color option that would set each bar a different color.

**Comment by michaeldmoore** [comment]
I did the release (v1.3.0), which might take a week or so before getting through the Grafana plugin release approval scheme.

While not an 'auto' color scheme exactly, it might go a long way towards your request - you can define each bar color according to an arbitrary set of rules, say by label name etc.

I think it solves most, if not all, of the things you were looking for.  Take a look and feel free to reopen this issue if you see a problem.  The updated README explains how it all works.
