### ISSUE TITLE
Join multiple label fields

### ISSUE THREAD

**Issue by paregupt** [michaeldmoore/michaeldmoore-multistat-panel#41]
Hi

Is there a way (or possible to enhance) to join multiple labels into a single label before displaying the data. Consider the example of water level in tanks in counties in cities.

```
water_level		Tank	city	county	
-----------		----	----	------	
20				A		city_1	county_1
30				B		city_2	county_1
40				C		city_3	county_1
60				D		city_4	county_1
70				A		city_1	county_2
10				B		city_2	county_2
90				A		city_1	county_3
50				B		city_2	county_3
```
Currently, the data is over-written when Label is Tank. Would joining Tank+city+county solve this issue?

Thanks and again, great panel!

**Comment by michaeldmoore** [comment]
This is a bit too specialized for incorporation in multistat itself - this control is by far one of the most complicated and versatile panels out there, but this would be just too much to make work in a generalized way.
On the other hand, the upcoming version 7 of Grafana has an aggregation feature that might handle this situation without me having to do this in the panel itself.

![image](https://user-images.githubusercontent.com/3724718/80996396-a4f3ad80-8e37-11ea-9295-4cdd437e54b5.png)
Other than seeing this feature and thinking of your request, I haven't looked into this in any details - but I think it looks very promising.

Grafana 7 is available as a beta version right now, so take a look and see if this does what you want.
Michael Moore

**Comment by paregupt** [comment]
Thanks Michael for taking a look. I have Grafana 7.0 beta running in lab. Will try it out. You already have made this panel immensely powerful so I can't be asking more. Thank you. Great work.
