### ISSUE TITLE
Feature Request- Make tooltip hover items selectable

### ISSUE THREAD

**Issue by Vishalckc** [michaeldmoore/michaeldmoore-multistat-panel#42]
Currently on hover, the tool tip can only be viewed. I want to make it selectable so that I can copy any value from the tooltip and do some further analysis on it. Any idea on how this can be done?
![image](https://user-images.githubusercontent.com/17704966/80485318-11127500-8951-11ea-9928-310310d9c5b9.png)

**Comment by michaeldmoore** [comment]
Interesting - I will look into this.

I have another request to add clickable links - I'll do this a the same
time and post an update.  This will take a few days though.

Cheers,

**Comment by Vishalckc** [comment]
Thanks for the acknowledgement! Let me know if any help required

Regards,
Vishal Verma

**Comment by michaeldmoore** [comment]
OK, I think it's all ready, minus updating the readme.md file to show the host of new features.
I got the clickable and selectable tooltip feature working - this was quite a bit trickier than I thought it would be.
![image](https://user-images.githubusercontent.com/3724718/80994544-b5565900-8e34-11ea-8cf6-bd1faf6fea7d.png)

I could add a number of new features at the same time though, including bar-level url links with parameter substitution using values from the selected bar - this is really cool, and compliments the panel-level links introduced in grafana 6 (I think).

I also did some work on the configuration screen layouts to better suit the revised UI in the upcoming Grafana version 7 release.

I have a few things to do still - updating the documentation and maybe trouble shooting a recent report I had saying grafana version 7 with a SQL Server data source is not being recognized properly.  For the moment, you should be able to pull the latest version from this github site.  I'd appreciate it if you could check this out and give me your feedback.  Probably not quite ready for production release, but it should be pretty close.

Regards,
Michael Moore

**Comment by Vishalckc** [comment]
You are awesome dude! Thanks a lot!!
Just one more question. I have my running image in docker with multistat plugin as Environment variable. Is there any version I need to specify to get these changes up and running? It dosen't work with my current image
"- GF_INSTALL_PLUGINS=grafana-clock-panel,michaeldmoore-multistat-panel"

**Comment by michaeldmoore** [comment]
Not sure what all that stuff means - I know what docker is and all that but
plugins as environment variables?  huh?

Nevermind,
The changes I made - with these new features etc. - this version hasn't yet
been submitted to grafana for review and defined in their plugin repo etc.
I still need to review and polish some things - especially adding
documentation in the readme.md file to explain how this all works etc.
Until then, you can only get the changes by downloading the zip file or
cloning the project from github, then expanding everything in your plugins
directory.  The latest commit - plugin version 1.4.0 - was made today to
the master branch.

As I said, you can check it out for test right now, but I'd wait for the
final polishing pieces and the grafana group review and approval which
should take a week or so before using it in a production capacity.

**Comment by Vishalckc** [comment]
I just tried unzipping it into my local machine folder and Voila! It works perfectly
Much better than before and smooth. Transition of hover is much better and I can copy the ID finally

Much Thanks!

**Comment by Vishalckc** [comment]
I will definitely wait for your submission. Let me know once it is sent for review to Grafana and available for usage. Thanks so much!
