### ISSUE TITLE
Error with grafana v7

### ISSUE THREAD

**Issue by thomas682** [michaeldmoore/michaeldmoore-multistat-panel#43]
Hello,

After update to 7 I get an error message 

I don’t use time series, I select table !
With the old grafana version (6.xx) all runs well!

If you can help me it will be great!

![540E4AD4-6C35-47CD-8F1A-92C9744FEDF2](https://user-images.githubusercontent.com/64754166/80926237-37437500-8d96-11ea-93a4-5486ce0be6ef.png)

What can I do?

Best regards 
Thomas

**Comment by thomas682** [comment]
That’s the result set and the second Screen is the sql set:


![913B195A-E528-4E30-B7A4-F596E37BFA0F](https://user-images.githubusercontent.com/64754166/80926305-b6d14400-8d96-11ea-99c2-93a04f9d6fec.png) 


![36C09964-C410-4EC1-8D4F-ADB7073B0097](https://user-images.githubusercontent.com/64754166/80926303-b2a52680-8d96-11ea-9621-43ec5672062a.png)

**Comment by michaeldmoore** [comment]
Interesting, I've been working with version 7 beta 1 and it seems to work
fine.

Let's look at the data your getting back from the query though.  Open the
query inspector and select the JSON tab.  You should see something like
this:

![image](https://user-images.githubusercontent.com/3724718/80966708-ed49a600-8e0c-11ea-8316-615b0ade0b82.png)

The key thing is that type: "table" value in the response.  This is what
tells the panel that the data set is a table-formatted data set instead of
a time series data set.

Press the button to copy the response to the clipboard and paste it into an
email so I can look and see what it is receiving.  Maybe something else is
going on with version 7 that I haven't seen so far.

Regards,
Michael Moore

**Comment by thomas682** [comment]
Hello Michael,

Your linked image does’ nt appears in the mail, following my JSON print.
Target seem's to be table format.

Remember, I have seen the graph before i updated grafana to v7!


Thanks for your quick help!

—————————————— JSON

{
  "datasource": "Microsoft SQL Server",
  "Aggregate": "all",
  "BarPadding": 5,
  "BaseLineColor": "rgb(158, 154, 154)",
  "BaseLineValue": 0,
  "CurveType": "Catmull-Rom",
  "DateFormat": "YYYY-MM-DD HH:mm:ss",
  "DateTimeColName": "",
  "DotColor": "#FF7383",
  "DotSize": 5,
  "EvenRowColor": "rgba(61, 61, 64, 0.78)",
  "FlashHighLimitBar": true,
  "FlashLowLimitBar": false,
  "GroupColName": "",
  "GroupCols": 0,
  "GroupGap": 5,
  "GroupLabelColor": "#ffffff",
  "GroupLabelFontSize": "100%",
  "GroupNameFilter": "",
  "GroupSortString": "",
  "HighAxisColor": "rgb(201, 185, 185)",
  "HighBarColor": "rgb(135, 74, 74)",
  "HighLimitBarColor": "#ff0000",
  "HighLimitBarFlashColor": "#ffa500",
  "HighLimitBarFlashTimeout": 2000,
  "HighLimitLineColor": "#FADE2A",
  "HighLimitValue": null,
  "HighSideMargin": 33,
  "Horizontal": false,
  "LabelColName": "time",
  "LabelColor": "#ffffff",
  "LabelFontSize": "70%",
  "LabelMargin": 30,
  "LabelNameFilter": "",
  "LableAngle": -90,
  "LineColor": "#C4162A",
  "LineWidth": 3,
  "LowAxisColor": "rgb(153, 153, 153)",
  "LowBarColor": "teal",
  "LowLimitBarColor": "#ff0000",
  "LowLimitBarFlashColor": "#ffa500",
  "LowLimitBarFlashTimeout": 200,
  "LowLimitLineColor": "#ff0000",
  "LowLimitValue": null,
  "LowSideMargin": 33,
  "MaxLineColor": "rgb(74, 232, 12)",
  "MaxLineValue": null,
  "MinLineValue": 0,
  "OddRowColor": "rgba(33, 33, 34, 0.92)",
  "OutOfRangeLabelColor": "#ffffff",
  "RecolorHighLimitBar": false,
  "RecolorLowLimitBar": false,
  "ScaleFactor": 1,
  "ShowBars": true,
  "ShowBaseLine": true,
  "ShowDate": false,
  "ShowGroupLabels": true,
  "ShowHighLimitLine": false,
  "ShowLabels": true,
  "ShowLeftAxis": true,
  "ShowLines": true,
  "ShowLowLimitLine": false,
  "ShowMaxLine": false,
  "ShowMinLine": false,
  "ShowRightAxis": true,
  "ShowTooltips": true,
  "ShowValues": true,
  "SortColName": "",
  "SortDirection": "ascending",
  "TZOffsetHours": 0,
  "TooltipDateFormat": "YYYY-MM-DD HH:mm:ss",
  "ValueColName": "value",
  "ValueColor": "#ffffff",
  "ValueDecimals": 1,
  "ValueFontSize": "70%",
  "ValuePosition": "top",
  "cacheTimeout": null,
  "gridPos": {
    "h": 6,
    "w": 18,
    "x": 0,
    "y": 10
  },
  "hideTimeOverride": false,
  "id": 15,
  "interval": "",
  "links": [],
  "pluginVersion": "6.4.3",
  "targets": [
    {
      "alias": "",
      "format": "table",
      "hide": false,
      "rawSql": "DECLARE @myStartDateParam as int;\nDECLARE @myEndDateParam as int;\nDECLARE @myId as int;\nDECLARE @myUTC as int;\n\nDECLARE @myDatapoint as varchar(255)\nSET @myDatapoint=\nCASE   \n         WHEN '$Bezug'='Öl'                    THEN 'javascript.0.Energie.EigenOelverbrauchszaehler'  \n         WHEN '$Bezug'='Wasser'                THEN 'javascript.0.Stall_Counter.Wasser_Gesamtzaehler'  \n         WHEN '$Bezug'='GartenWasser'          THEN 'javascript.0.Stall_Counter.GartenWasser_Gesamtzaehler' \n         WHEN '$Bezug'='StromBezug'            THEN 'javascript.0.EnergieBericht.Bezug.Zaehlerstand.kumuliert'\n         WHEN '$Bezug'='StromVerbrauch'        THEN 'javascript.0.Energie.Eigenverbrauchszaehler'  \n         WHEN '$Bezug'='Solar'                 THEN 'javascript.0.SunnyWebbox.Gesamtertrag'  \n         WHEN '$Bezug'='StromEinspeisung'      THEN 'javascript.0.EnergieBericht.Einspeisung.Zaehlerstand.kumuliert'\n  ELSE 'x'  \nEND;\n\nSelect @myId = id from datapoints where name=@myDatapoint;\n\nDECLARE @myFaktor as int;\nselect @myFaktor = 1;\nif '$Bezug'='Wasser' or '$Bezug'='GartenWasser'\nBEGIN\n    select @myFaktor = 1000;\nEND\n\n\nSET @myStartDateParam = $__unixEpochFrom();\nSET @myEndDateParam = $__unixEpochTo();\nset @myUTC=datediff(s,GETDATE(),GETUTCDATE())+0;\n\n-- und nun holen wir von dem Objekt alle Werte gruppiert nach Monaten\nSELECT \n\tSUBSTRING(max(convert(varchar(13), dateadd(s,(n.ts/1000),'19700101 01:00:00'), 126)),9,6) as time,\n\t-- \n\t(max(val)-min(val))*@myFaktor AS value\nFROM ts_number n\t\nWHERE  id=@myId and val>=0\nAND ((n.ts/1000))>(@myStartDateParam) AND ((n.ts/1000))<(@myEndDateParam)\nGROUP BY convert(varchar(13), dateadd(s,n.ts/1000,'19700101'),126)\n--ORDER BY convert(varchar(13), dateadd(s,n.ts/1000,'19700101'), 126) DESC",
      "refId": "A"
    }
  ],
  "timeFrom": "24h",
  "timeShift": null,
  "title": "$Bezug 24h",
  "transparent": true,
  "type": "michaeldmoore-multistat-panel",
  "fieldConfig": {
    "defaults": {
      "custom": {}
    },
    "overrides": []
  },
  "BaseLineWidth": 1,
  "HighAxisWidth": 1,
  "RecolorColName": null,
  "HighLmitLineWidth": 1,
  "LowAxisWidth": 1,
  "LowLmitLineWidth": 1,
  "MaxLineWidth": 1,
  "MinLineColor": "#ff0000",
  "MinLineWidth": 1,
  "RecolorRules": []
}



Regards,
Thomas

> Am 04.05.2020 um 01:06 schrieb michaeldmoore <notifications@github.com>:
> 
> 
> Interesting, I've been working with version 7 beta 1 and it seems to work
> fine.
> 
> Let's look at the data your getting back from the query though. Open the
> query inspector and select the JSON tab. You should see something like
> this:
> [image: image.png]
> 
> The key thing is that type: "table" value in the response. This is what
> tells the panel that the data set is a table-formatted data set instead of
> a time series data set.
> 
> Press the button to copy the response to the clipboard and paste it into an
> email so I can look and see what it is receiving. Maybe something else is
> going on with version 7 that I haven't seen so far.
> 
> Regards,
> Michael Moore
> 
>

**Comment by michaeldmoore** [comment]
Thanks for the update Thomas, and for the panel JSON.  I can see you are requesting table data from SQL Server.  What I can't see though is what data Grafana passes through the datasource to the panel.  I suspect the SQL Server data source or something else in grafana version 7 is somehow not passing the type:"table" attribute through - or possibly it is spelled differently, coming from Germany (I assume).  I'm in the UK and horrified by all the brexit nonsense, so greetings from a fellow european!) 
The image would have shown what I mean, and I'll try again here in case this time it works

![image](https://user-images.githubusercontent.com/3724718/80966229-fede7e00-8e0b-11ea-863b-61b9fd38cc24.png)

I think this should work.  What I need to see is the JSON from the query inspector.
In Grafana 7, open the query inspector, select the query tab, click the refresh button then the 'copy to clipboard' button.  And paste the JSON in a reply.  Thanks.

The critical bit is the type:"table" indicator.  If this has changed, I'll need to modify the way multistat checks the received data format.

I can't run SQL Server here today, so I'm counting on you to be my eyes-and-ears on this.
Thanks again
Michael Moore

**Comment by thomas682** [comment]
Hello Michael,

of course I will provide you with that query result, thanks for your efforts!

query result:
----------------

{
  "request": {
    "url": "api/tsdb/query",
    "method": "POST",
    "data": {
      "from": "1588513664448",
      "to": "1588600064448",
      "queries": [
        {
          "refId": "A",
          "intervalMs": 60000,
          "maxDataPoints": 2277,
          "datasourceId": 1,
          "rawSql": "DECLARE @myStartDateParam as int;\nDECLARE @myEndDateParam as int;\nDECLARE @myId as int;\nDECLARE @myUTC as int;\n\nDECLARE @myDatapoint as varchar(255)\nSET @myDatapoint=\nCASE   \n         WHEN 'Solar'='Öl'                    THEN 'javascript.0.Energie.EigenOelverbrauchszaehler'  \n         WHEN 'Solar'='Wasser'                THEN 'javascript.0.Stall_Counter.Wasser_Gesamtzaehler'  \n         WHEN 'Solar'='GartenWasser'          THEN 'javascript.0.Stall_Counter.GartenWasser_Gesamtzaehler' \n         WHEN 'Solar'='StromBezug'            THEN 'javascript.0.EnergieBericht.Bezug.Zaehlerstand.kumuliert'\n         WHEN 'Solar'='StromVerbrauch'        THEN 'javascript.0.Energie.Eigenverbrauchszaehler'  \n         WHEN 'Solar'='Solar'                 THEN 'javascript.0.SunnyWebbox.Gesamtertrag'  \n         WHEN 'Solar'='StromEinspeisung'      THEN 'javascript.0.EnergieBericht.Einspeisung.Zaehlerstand.kumuliert'\n  ELSE 'x'  \nEND;\n\nSelect @myId = id from datapoints where name=@myDatapoint;\n\nDECLARE @myFaktor as int;\nselect @myFaktor = 1;\nif 'Solar'='Wasser' or 'Solar'='GartenWasser'\nBEGIN\n    select @myFaktor = 1000;\nEND\n\n\nSET @myStartDateParam = $__unixEpochFrom();\nSET @myEndDateParam = $__unixEpochTo();\nset @myUTC=datediff(s,GETDATE(),GETUTCDATE())+0;\n\n-- und nun holen wir von dem Objekt alle Werte gruppiert nach Monaten\nSELECT \n\tSUBSTRING(max(convert(varchar(13), dateadd(s,(n.ts/1000),'19700101 01:00:00'), 126)),9,6) as time,\n\t-- \n\t(max(val)-min(val))*@myFaktor AS value\nFROM ts_number n\t\nWHERE  id=@myId and val>=0\nAND ((n.ts/1000))>(@myStartDateParam) AND ((n.ts/1000))<(@myEndDateParam)\nGROUP BY convert(varchar(13), dateadd(s,n.ts/1000,'19700101'),126)\n--ORDER BY convert(varchar(13), dateadd(s,n.ts/1000,'19700101'), 126) DESC",
          "format": "table"
        }
      ]
    }
  },
  "response": {
    "results": {
      "A": {
        "refId": "A",
        "meta": {
          "rowCount": 25,
          "sql": "DECLARE @myStartDateParam as int;\nDECLARE @myEndDateParam as int;\nDECLARE @myId as int;\nDECLARE @myUTC as int;\n\nDECLARE @myDatapoint as varchar(255)\nSET @myDatapoint=\nCASE   \n         WHEN 'Solar'='Öl'                    THEN 'javascript.0.Energie.EigenOelverbrauchszaehler'  \n         WHEN 'Solar'='Wasser'                THEN 'javascript.0.Stall_Counter.Wasser_Gesamtzaehler'  \n         WHEN 'Solar'='GartenWasser'          THEN 'javascript.0.Stall_Counter.GartenWasser_Gesamtzaehler' \n         WHEN 'Solar'='StromBezug'            THEN 'javascript.0.EnergieBericht.Bezug.Zaehlerstand.kumuliert'\n         WHEN 'Solar'='StromVerbrauch'        THEN 'javascript.0.Energie.Eigenverbrauchszaehler'  \n         WHEN 'Solar'='Solar'                 THEN 'javascript.0.SunnyWebbox.Gesamtertrag'  \n         WHEN 'Solar'='StromEinspeisung'      THEN 'javascript.0.EnergieBericht.Einspeisung.Zaehlerstand.kumuliert'\n  ELSE 'x'  \nEND;\n\nSelect @myId = id from datapoints where name=@myDatapoint;\n\nDECLARE @myFaktor as int;\nselect @myFaktor = 1;\nif 'Solar'='Wasser' or 'Solar'='GartenWasser'\nBEGIN\n    select @myFaktor = 1000;\nEND\n\n\nSET @myStartDateParam = 1588513664;\nSET @myEndDateParam = 1588600064;\nset @myUTC=datediff(s,GETDATE(),GETUTCDATE())+0;\n\n-- und nun holen wir von dem Objekt alle Werte gruppiert nach Monaten\nSELECT \n\tSUBSTRING(max(convert(varchar(13), dateadd(s,(n.ts/1000),'19700101 01:00:00'), 126)),9,6) as time,\n\t-- \n\t(max(val)-min(val))*@myFaktor AS value\nFROM ts_number n\t\nWHERE  id=@myId and val>=0\nAND ((n.ts/1000))>(@myStartDateParam) AND ((n.ts/1000))<(@myEndDateParam)\nGROUP BY convert(varchar(13), dateadd(s,n.ts/1000,'19700101'),126)\n--ORDER BY convert(varchar(13), dateadd(s,n.ts/1000,'19700101'), 126) DESC"
        },
        "series": null,
        "tables": [
          {
            "columns": [
              {
                "text": "time"
              },
              {
                "text": "value"
              }
            ],
            "rows": [
              [
                "04T10",
                2.1171875
              ],
              [
                "03T14",
                0.765625
              ],
              [
                "04T04",
                0
              ],
              [
                "03T23",
                0
              ],
              [
                "04T00",
                0
              ],
              [
                "03T20",
                0
              ],
              [
                "03T21",
                0
              ],
              [
                "04T07",
                0.640625
              ],
              [
                "04T14",
                0.765625
              ],
              [
                "03T18",
                0.390625
              ],
              [
                "03T15",
                3.296875
              ],
              [
                "04T09",
                1.9765625
              ],
              [
                "03T19",
                0.03125
              ],
              [
                "04T02",
                0
              ],
              [
                "03T22",
                0
              ],
              [
                "04T13",
                0.2734375
              ],
              [
                "03T16",
                2.2734375
              ],
              [
                "04T01",
                0
              ],
              [
                "04T06",
                0.515625
              ],
              [
                "04T08",
                1.734375
              ],
              [
                "03T17",
                0.78125
              ],
              [
                "04T12",
                3.4609375
              ],
              [
                "04T03",
                0
              ],
              [
                "04T05",
                0.1015625
              ],
              [
                "04T11",
                3.0234375
              ]
            ],
            "type": "table",
            "refId": "A",
            "meta": {
              "rowCount": 25,
              "sql": "DECLARE @myStartDateParam as int;\nDECLARE @myEndDateParam as int;\nDECLARE @myId as int;\nDECLARE @myUTC as int;\n\nDECLARE @myDatapoint as varchar(255)\nSET @myDatapoint=\nCASE   \n         WHEN 'Solar'='Öl'                    THEN 'javascript.0.Energie.EigenOelverbrauchszaehler'  \n         WHEN 'Solar'='Wasser'                THEN 'javascript.0.Stall_Counter.Wasser_Gesamtzaehler'  \n         WHEN 'Solar'='GartenWasser'          THEN 'javascript.0.Stall_Counter.GartenWasser_Gesamtzaehler' \n         WHEN 'Solar'='StromBezug'            THEN 'javascript.0.EnergieBericht.Bezug.Zaehlerstand.kumuliert'\n         WHEN 'Solar'='StromVerbrauch'        THEN 'javascript.0.Energie.Eigenverbrauchszaehler'  \n         WHEN 'Solar'='Solar'                 THEN 'javascript.0.SunnyWebbox.Gesamtertrag'  \n         WHEN 'Solar'='StromEinspeisung'      THEN 'javascript.0.EnergieBericht.Einspeisung.Zaehlerstand.kumuliert'\n  ELSE 'x'  \nEND;\n\nSelect @myId = id from datapoints where name=@myDatapoint;\n\nDECLARE @myFaktor as int;\nselect @myFaktor = 1;\nif 'Solar'='Wasser' or 'Solar'='GartenWasser'\nBEGIN\n    select @myFaktor = 1000;\nEND\n\n\nSET @myStartDateParam = 1588513664;\nSET @myEndDateParam = 1588600064;\nset @myUTC=datediff(s,GETDATE(),GETUTCDATE())+0;\n\n-- und nun holen wir von dem Objekt alle Werte gruppiert nach Monaten\nSELECT \n\tSUBSTRING(max(convert(varchar(13), dateadd(s,(n.ts/1000),'19700101 01:00:00'), 126)),9,6) as time,\n\t-- \n\t(max(val)-min(val))*@myFaktor AS value\nFROM ts_number n\t\nWHERE  id=@myId and val>=0\nAND ((n.ts/1000))>(@myStartDateParam) AND ((n.ts/1000))<(@myEndDateParam)\nGROUP BY convert(varchar(13), dateadd(s,n.ts/1000,'19700101'),126)\n--ORDER BY convert(varchar(13), dateadd(s,n.ts/1000,'19700101'), 126) DESC"
            }
          }
        ],
        "dataframes": null
      }
    }
  }
}

and a hardcopy of the screen - it seems result is return as „tables"

<img width="563" alt="FFBD98F6-AD57-463E-A27A-DBFF8B17F8C1" src="https://user-images.githubusercontent.com/64754166/80987391-4415a680-8e32-11ea-9ade-d7df3d2d5fc5.png">



If I compare your image with my their seems a quit lot differences ?
f.e. response -> array  vs   response > object 

Because my knowledge is limited regarding JSON and Grafana, please feel free for further request of informations and I try to support you!

regard
Thomas

**Comment by thomas682** [comment]
Hello Michael,

i try to debug js in chrome...

data[0].type does not appears in the json result!

![2020-05-07 16_20_23-Überblick - Grafana](https://user-images.githubusercontent.com/64754166/81305781-08235100-907f-11ea-8928-96b54297517e.png)


hope i can support you with the analysing ...

regards
thomas

**Comment by thomas682** [comment]
Hello Michael,

i downgrade to 6.4.3 an your control works again

error: grafana-7.0.0-beta1.windows-amd64
error: grafana-7.0.0-beta3.windows-amd64
ok: grafana-6.7.3.windows-amd64

The structure is changed in V7, following the js debugger screenshot: 

<img width="454" alt="Screenshot at May 10 13-08-03" src="https://user-images.githubusercontent.com/64754166/81497567-9ab23300-92bf-11ea-893a-9829efe5eee7.png">

regards
thomas

**Comment by michaeldmoore** [comment]
Thank you for these recent updates - I think there might be something going on with the data retured by the SQL Server datasource.  Luckily, I'm now set up to check this out here too, so I should be able to look at this insome detail soon.##Right now, I'm tied up with some more pressing deliverables so it might take some days before I can get to this.

Until then - watch this space.
Regards
Michael Moore

**Comment by michaeldmoore** [comment]
I just installed SQL Server to check this out and it works perfectly - with version 7 beta 1 and the newest Beta3.  Note Multistat is currently at version 1.4.0, released April 4th.

![image](https://user-images.githubusercontent.com/3724718/81806610-9a5ea580-9514-11ea-970e-44126af4671b.png)


I'm closing this issue.  Feel free to re-open it if you think there is still something wrong, but first look carefully at your query - maybe there is something odd that I can't see from your samples.
Regards,
Michael Moore

**You can reproduce this using the following sample data.**

For this test, I'm using a very simple SQL Server table created using this simple sccript:
```
CREATE TABLE [Sensors](
	[Region] [varchar](20) NOT NULL,
	[Sensor] [varchar](20) NOT NULL,
	[Temperature] [float] NOT NULL,
	[Humidity] [float] NOT NULL,
	[Pressure] [float] NOT NULL,
	[Color] [varchar](20) NULL
) ON [PRIMARY]
GO
INSERT [Sensors] ([Region], [Sensor], [Temperature], [Humidity], [Pressure], [Color]) VALUES (N'East', N'Top', 86, 23, 1008, N'Yellow')
INSERT [Sensors] ([Region], [Sensor], [Temperature], [Humidity], [Pressure], [Color]) VALUES (N'East', N'Middle', 82, 26, 1020, NULL)
INSERT [Sensors] ([Region], [Sensor], [Temperature], [Humidity], [Pressure], [Color]) VALUES (N'East', N'Bottom', 71, 18, 980, N'Red')
INSERT [Sensors] ([Region], [Sensor], [Temperature], [Humidity], [Pressure], [Color]) VALUES (N'West', N'Top', 45, 87, 1011, NULL)
INSERT [Sensors] ([Region], [Sensor], [Temperature], [Humidity], [Pressure], [Color]) VALUES (N'West', N'Middle', 39, 77, 1032, NULL)
INSERT [Sensors] ([Region], [Sensor], [Temperature], [Humidity], [Pressure], [Color]) VALUES (N'West', N'Bottom', 57, 44, 1010, NULL)
GO
```


**The query is then simply:**
`SELECT * FROM Sensors`


Looking at the table-formatted data set returned, I get this:
```
{
  "request": {
    "url": "api/tsdb/query",
    "method": "POST",
    "data": {
      "from": "1589347509670",
      "to": "1589369109670",
      "queries": [
        {
          "refId": "A",
          "intervalMs": 60000,
          "maxDataPoints": 973,
          "datasourceId": 2,
          "rawSql": "select * from sensors",
          "format": "table"
        }
      ]
    }
  },
  "response": {
    "results": {
      "A": {
        "refId": "A",
        "meta": {
          "rowCount": 6,
          "sql": "select * from sensors"
        },
        "series": null,
        "tables": [
          {
            "columns": [
              { "text": "Region" },
              { "text": "Sensor" },
              { "text": "Temperature" },
              { "text": "Humidity" },
              { "text": "Pressure" },
              { "text": "Color" }
            ],
            "rows": [
              [ "East", "Top",  86,  23, 1008, "Yellow" ],
              [ "East", "Middle",  82, 26, 1020, null ],
              [ "East", "Bottom", 71,18, 980, "Red" ],
              [ "West","Top", 45, 87, 1011, null ],
              [ "West", "Middle", 39, 77, 1032, null ],
              [ "West", "Bottom", 57, 44, 1010, null ]
            ],
            "type": "table",
            "refId": "A",
            "meta": {
              "rowCount": 6,
              "sql": "select * from sensors"
            }
          }
        ],
        "dataframes": null
      }
    }
  }
}

```
Note that this has the columns property, which is one of the ways Multistat confirms that this is, indeed, a Table-formatted data set

My panel JSON is as follows:
```
{
  "datasource": "Microsoft SQL Server",
  "type": "michaeldmoore-multistat-panel",
  "title": "SQL Server Test",
  "gridPos": {
    "x": 0,
    "y": 0,
    "w": 12,
    "h": 9
  },
  "id": 23763571993,
  "targets": [
    {
      "refId": "A",
      "format": "table",
      "alias": "",
      "rawSql": "select * from sensors",
      "hide": false
    }
  ],
  "fieldConfig": {
    "defaults": {
      "custom": {}
    },
    "overrides": []
  },
  "timeFrom": null,
  "timeShift": null,
  "BarPadding": 10,
  "BaseLineColor": "#ff0000",
  "BaseLineWidth": 1,
  "BaseLineValue": null,
  "DateTimeColName": "date",
  "DateFormat": "YYYY-MM-DD HH:mm:ss",
  "TooltipDateFormat": "YYYY-MM-DD HH:mm:ss",
  "FlashHighLimitBar": false,
  "FlashLowLimitBar": false,
  "HighAxisColor": "#ffffff",
  "HighAxisWidth": 1,
  "HighBarColor": "rgb(120, 128, 0)",
  "RecolorColName": "Color",
  "HighLimitBarColor": "#ff0000",
  "HighLimitBarFlashColor": "#ffa500",
  "HighLimitBarFlashTimeout": 1000,
  "HighLimitLineColor": "#ff0000",
  "HighLimitValue": null,
  "HighLmitLineWidth": 1,
  "HighSideMargin": 22,
  "Horizontal": false,
  "LabelColName": "Sensor",
  "LabelNameFilter": "",
  "LabelColor": "#ffffff",
  "OutOfRangeLabelColor": "#ffffff",
  "GroupLabelColor": "#ffffff",
  "LabelFontSize": "100%",
  "GroupLabelFontSize": "200%",
  "GroupGap": 5,
  "LabelMargin": null,
  "Links": [],
  "LowAxisColor": "#ffffff",
  "LowAxisWidth": 1,
  "LowBarColor": "teal",
  "LowLimitBarColor": "#ff0000",
  "LowLimitBarFlashColor": "#ffa500",
  "LowLimitBarFlashTimeout": 200,
  "LowLimitLineColor": "#ff0000",
  "LowLimitValue": null,
  "LowLmitLineWidth": 1,
  "LowSideMargin": 22,
  "MaxLineColor": "rgb(74, 232, 12)",
  "MaxLineWidth": 1,
  "MaxLineValue": null,
  "MinLineColor": "#ff0000",
  "MinLineWidth": 1,
  "MinLineValue": null,
  "RecolorHighLimitBar": false,
  "RecolorLowLimitBar": false,
  "RecolorRules": [],
  "ShowBaseLine": false,
  "ShowDate": false,
  "Aggregate": "last",
  "ShowHighLimitLine": false,
  "ShowLabels": true,
  "ShowGroupLabels": true,
  "ShowLeftAxis": true,
  "ShowLowLimitLine": false,
  "ShowMaxLine": false,
  "ShowMinLine": false,
  "ShowRightAxis": true,
  "ShowTooltips": true,
  "ShowValues": true,
  "SortColName": "value",
  "SortDirection": "ascending",
  "TZOffsetHours": 0,
  "ValueColName": "Humidity",
  "ValueDecimals": 2,
  "ValueColor": "#ffffff",
  "ValueFontSize": "100%",
  "OddRowColor": "rgba(33, 33, 34, 0.92)",
  "EvenRowColor": "rgba(61, 61, 64, 0.78)",
  "OutlineColor": "rgba(245, 255, 0, 0.1)",
  "GroupSortString": "",
  "GroupCols": 0,
  "GroupNameFilter": "",
  "ScaleFactor": 1,
  "ValuePosition": "top",
  "LableAngle": 0,
  "ShowBars": true,
  "ShowLines": false,
  "LineWidth": 5,
  "LineColor": "blue",
  "DotSize": 10,
  "DotColor": "white",
  "CurveType": "Monotone",
  "GroupColName": "Region"
}
```
