### ISSUE TITLE
Hover Tooltip moves out of screen in boundary cases

### ISSUE THREAD

**Issue by Vishalckc** [michaeldmoore/michaeldmoore-multistat-panel#46]
![image](https://user-images.githubusercontent.com/17704966/81933277-0577ad00-95e5-11ea-8ce5-6c8e929a6e4a.png)
The hover Tool tip when moving near to edge of the multistat graph causes the tooltip position to move out of the screen (in my case it went left). Please see to this!

**Comment by michaeldmoore** [comment]
Try the latest version of Multistat  v 1.4.0.  It has several enhancements
regarding tooltips including styling, selectable text and clickable URL
links.

I think the off-the-screen issue might still be a problem under some
circumstances, but I advise you to try it and see.

Send me a screenshot if you still are having trouble and I'll put it on my
list of things to take care of in the next release.

**Comment by michaeldmoore** [comment]
Your right - this is something I have to work on.

As it happens, I have a new version v 1.4.0 checked into github with a
number of enhancements to tooltips.  Improved styling, selectable text and
clickable url links.  I've held off submitting this to Grafana for approval
and integration into the Grafana plugin repo while I work on updating the
README file.

I'm not 100% sure the issue you ran into with the tooltips running off the
side of the screen is completely fixed, but the improved styling should
make this better at least.

I will make a point of addressing this run-off issue though before
submitting it as an official release.
In the meantime, try grabbing version 1.4.0 from my github repo directly (
https://github.com/michaeldmoore/michaeldmoore-multistat-panel/archive/master.zip
) and see what you think.  Any constructive feedback, greatly appreciated :)

**Comment by michaeldmoore** [comment]
Also - I created Multistat for some quite complex monitoring applications,
with grouping and out-of-range alerting etc.  For a bog simple bar chart,
you *might *be better off looking at the new bar-guage panel built into
Grafana.  https://grafana.com/docs/grafana/latest/features/panels/bar_gauge/

**Comment by Vishalckc** [comment]
Sure Michael,

Thanks for your early reply. I will try to check and get back to you soon

Take care
Regards,
Vishal Verma

**Comment by michaeldmoore** [comment]
OK, I finally have this working - a surprisingly complicated system as it turns out.  I just have a bit of work to finish up on the readme file, then I'll release it to Grafana for approval and integration with the official panel repository.

Let me know if you run into any problems with this, or if you find the minimal documentation unclear.

![image](https://user-images.githubusercontent.com/3724718/82230928-4e509e00-9924-11ea-909c-6b0bda7bb0d9.png)
 
![image](https://user-images.githubusercontent.com/3724718/82231097-9079df80-9924-11ea-85fc-1d5d8e5e003f.png)

**Comment by Vishalckc** [comment]
Thank you so much Michael. This looks great
