### ISSUE TITLE
Broken with Grafana 7.1

### ISSUE THREAD

**Issue by dguendisch** [michaeldmoore/michaeldmoore-multistat-panel#51]
Tried to upgrade my grafana to 7.1 and noticed that the multistat panel does not show any data anymore.
Tried to create a new dashboard, immediately upon selecting the multistat plugin visualization, the following error screen is shown:
![image](https://user-images.githubusercontent.com/30311254/87874889-bfb4d780-c9cd-11ea-92eb-235335dd6590.png)

(Btw. everything worked fine on grafana 7.0.4)

**Comment by michaeldmoore** [comment]
I'll take a look and see if they've broken anything with this version of
Grafana (this does happen fairly often, I'm afraid).

In the mean time, make sure you are running the latest version of multistat
- maybe this is a known issue that I fixed already.

Excuse me if it takes a couple of days before I can look into this further.

Cheers
Michael Moore

**Comment by poldown** [comment]
Confirming that it happens for me too on 7.1.0 with Multistat version 1.4.0

**Comment by paregupt** [comment]
Same here. If you want me to try out or help with some verification, I am happy to help.

**Comment by michaeldmoore** [comment]
Thanks for the heads up all.  I found and fixed the problem - apparently, in the transition from Angular to React, Grafana 7.1 broke some backwards-compatibility features;  in this case, the constructor-injected variableSvr parameter.

I released a fix in the form of Multistat 1.4.1 to address this.

It might take Grafana some days or even weeks before they process and approve this fixed version and add it to the official panel repository.  You can download it here though, if you need it more quickly.

Regards
Michael Moore

**Comment by dguendisch** [comment]
Thanks a lot!!
