### ISSUE TITLE
Getting issue while selecting status panel

### ISSUE THREAD

**Issue by sunil3404** [michaeldmoore/michaeldmoore-multistat-panel#53]
Details
TypeError: Cannot read property 'slice' of undefined

tried on grafana version '6.7.3' and '7.1.1'
![image](https://user-images.githubusercontent.com/54355368/89630274-bfb54280-d8bc-11ea-9671-3eda47d7608f.png)

**Comment by michaeldmoore** [comment]
I don't know what you expect, giving an error report like this - how can
anyone help you if you can't be bothered to give even the smallest amount
of details?

Nevertheless, I'll spend several times as long typing this answer as you
did in generating the problem report.

Usually, when people have weird problems like this, on things that everyone
else has been managing to use successfully over months or years, and over
many versions - turn out to be something to do with the renning
environment.  More often than not, I find problems with the version of node
they have installed.  The latest LTS (long term stable) release of node is
version 12.18.3  (There is a 'cutting edge' version available, 14.x.x too,
but that is known to have problems with Grafana - so don't use it.)

To find the version you have installed, open a terminal or cmd window any
type in node --version

If this doesn't do the trick, feel free to reply to this, but give details
such as what version of multistat you are running, what your panel
configuration looks like (you can export the panel settings as JSON for
this) and most importantly, what you are doing to get the error message to
appear.

'split' is a standard javascript string function used in any number of
libraries imported into multistat.  Surprisingly though, I don't actually
call this function directly anywhere in multistat - leading me to suspect
once more, something to do with node itself.
