### ISSUE TITLE
Recolor options not showing

### ISSUE THREAD

**Issue by TheSystech** [michaeldmoore/michaeldmoore-multistat-panel#60]
I've verified (as best I can) that I'm running the latest plugin and I'm running the latest version of Grafana, but the REcolor options don't even show up for me in the Columns section.

**Comment by michaeldmoore** [comment]
I can't look at this now, but REcoloring was introduced with Multistat
version 1.3.0. and should appear - as you say - in the Columns config
section.

https://github.com/michaeldmoore/michaeldmoore-multistat-panel/blob/master/README.md#Recolor-Rules

The newer versions of Grafana moved configuration options to the right hand
side and maybe you'll need to make the window wider to see everything (I
remember the change to Grafana did cause some layout wrapping issues)

If you still can't see it, make a new dashboard and add the plugin-list
panel - this should confirm the exact version you have loaded.  It never
hurts to check the obvious.

After that, if you still have trouble, check the debug console (F12 in
Chrome and - I think - I.E. too).  Look for anything suggesting an error.

And if you need help - add some screen captures.  A general 'this don't
work' issue is not really much use.

Regards,
Michael Moore

**Comment by TheSystech** [comment]
Yeah.. sorry I just started this as a placeholder while I gathered more data. I wasn't expecting you to look at it quite so soon :)  

The plugin is up to date: 
![image](https://user-images.githubusercontent.com/15459755/99826960-a8722c00-2b1e-11eb-9e39-60d0488260fa.png)

The Debugger console in Chrome doesn't really show anything helpful at all:
![image](https://user-images.githubusercontent.com/15459755/99827368-259da100-2b1f-11eb-9d79-4d467f18b250.png)

And the Section just flat doesn't *show* in the Columns section... The last thing that shows is Sort Col.
![image](https://user-images.githubusercontent.com/15459755/99827439-39e19e00-2b1f-11eb-9327-57429e3a7ac2.png)

It doesn't matter how wide I make the browser window, etc..

**Comment by TheSystech** [comment]
Interestingly enough it may be a Chrome issue...  I just decided to try it in Chromium based edge and it works there... Odd.
