### ISSUE TITLE
Vertical gap between groups

### ISSUE THREAD

**Issue by FelixKulish** [michaeldmoore/michaeldmoore-multistat-panel#64]
Hi. First of all great plugin.
I just have a question about "Vertical gap between groups", I did find a horizontal one, but didn't find a vertical.
The rows are very close together and I wanted to put put some gap between the rows.
Did I miss something?
Thank in advance.

**Comment by michaeldmoore** [comment]
If you define a grouping column, Multistat will create multiple sub-panels
- one for each group.  The 'gap between groups' setting controls how much
each of these sub-panels are separated.
Within a sub-panel (or, if you're not grouping - within the panel), there
is a setting for the percentage of the space allocated to a given label,
occupied by the visible bar.  Sorry if this is still confusing, but the
idea is very simple.  If the bar width percentage (or whatever I called it)
is set to 100%, each bar buts up against the bar next to it.  If this is
set to 50%, then there is a gap between bars equal to the width of the bar
itself.

As to the vertical/horizontal thing, everything works (or should work) more
or less identically in both orientations.  There may be some confusion by
terms such a 'upper' and 'lower' etc., that end up being twisted through 90
degrees etc., but I'm sure anyone can figure this stuff out.

If you really still don't see what you want, send me a screen capture of
what you have and sketch up what you want it to look like.  I'll see if I
can point you in the right direction.
Very glad you found the panel useful though.
Michael Moore

**Comment by FelixKulish** [comment]
Thanks for the fast response. 
I didn't find the property that you spoked about.
![image](https://user-images.githubusercontent.com/18226477/115515709-136e8d00-a28e-11eb-9e66-9c02c886bb04.png)
this is my panel, I want to increase the space between the rows (red marking on the picture)
I think that you misunderstood me, I want to increase the gap between group rows, not between bars in one of the groups

**Comment by michaeldmoore** [comment]
Interesting, and with the picture, I understand what you are talking about
now.   There is no setting for this in the current version, but adding it
didn't take long.

Look out for the next version (1.7.2) which I'll try to get released
today.  It might take a few weeks to get through Grafana's approval
process.  In the meantime, you might download it directly from github once
everything is posted and signed properly.

[image: image.png]

**Comment by FelixKulish** [comment]
Thanks a lot
another small thing, can there be an option to style the group labels text? (now there is a color and size option), maybe add Bold option and font type can also be added?

**Comment by michaeldmoore** [comment]
Try playing with the CSS file.  It might mess up the signing tag, but you
should be able to override just about anything there.

**Comment by FelixKulish** [comment]
Ok
Thanks a lot for you very fast help
